### ISSUE TITLE
within-host diversity analysis : one individual, different time-points

### ISSUE THREAD

**Issue by PegahDan** [chasewnelson/SNPGenie#62]
Hi !
I read your paper and a few of those citing you. I think your tool could be useful for my analysis. But I am still new to all of this.
I have multiple viral samples isolated at different time points from one infected patient who has received treatment through the infection. And I would like to know if there is a pressure of selection after the treatment, and in which case measure the within-host evolution.
I used your tool, the snpgenie.pl script, on each of my samples VCF file.  The tool ran perfectly ! The idea, to me, was to measure the nucleotide diversity for each sample (i.e. time point isolation) and then compare the variations of these metrics over time. 
However, I have a few questions.
1) Does it make sense to use SNPGenie in this case?
2) I'm not sure I understood the difference between the pi_N et the mean_dN_vs_ref values. I know it has been explained on issue #46, but I still have trouble seeing the difference, and especially in my case how to interpret these metrics.
I apologize in advance for these (dummy) questions.

Thanks for the help !

**Comment by singing-scientist** [comment]
Greetings, @PegahDan ! Thanks very much for the questions. I'm so glad the tool ran easily. The idea seems very exciting, i.e., you track the change in π (or πN and πS separately; or the frequencies of specific variants; etc.) over time in the patient. Specifically with respect to your questions:

1. Yes, insofar as I understand your study, it makes sense to use SNPGenie. I am assuming each time point is a deeply sequenced (high-coverage) sample, for which single nucleotide variants (SNV) are being inferred and used as input to estimate π. You will want to make sure to apply appropriate quality control metrics to these SNV calls to make sure you remove possible sequencing errors. Some studies do something simple like eliminating all variants below frequencies of 1% (or 2%, or even 5%); require a minimum coverage (read depth of 100, for example); and other rules. I have also just finished a new tool called VCFgenie that does this (and more) if you're interested in trying it out: https://github.com/chasewnelson/VCFgenie 

2. π is the mean number of differences per site among ALL sequences. For example, if there are three sequences, you would make all possible comparisons (s1/s2, s1/s3, and s2/s3) and then take the average value. Contrarily, for d vs. ref, ONE sequence is chosen as the reference, and the question is the average divergence from that one sequence. For example, suppose s1 is chosen at the reference (e.g., it could be time point 0; or the known inoculum sequence; or something else). In that case, d vs ref would be the mean of only s1/s2 and s1/s3. The comparison s2/s3 would NOT be included because neither is the reference, and the question being asked is specifically about distance from the reference. Does that help?

My pleasure, let me know --
Chase

**Comment by PegahDan** [comment]
Thanks @singing-scientist for the rapid and well-explained feedback!

1. Yes I filtered the variants with a minimum coverage of 100x and a frequency minimum threshold of 10% and also used a strand bias filter with LoFreq (also used for the variant calling step). Great I'll try your VCFgenie tool !

2. I now better understand the definition and the difference between π and the d vs ref estimations. However, I'm having doubts on how I ran the snpgenie.pl script. I ran it for each sample such as :
```
SNPGenie/snpgenie.pl --vcfformat=3 --snpreport=D0_snv_filter.vcf --fastafile=ref.genome --gtffile=ref_genes.gtf 
SNPGenie/snpgenie.pl --vcfformat=3 --snpreport=D29_snv_filter.vcf --fastafile=ref.genome --gtffile=ref_genes.gtf 
SNPGenie/snpgenie.pl --vcfformat=3 --snpreport=D50_snv_filter.vcf --fastafile=ref.genome --gtffile=ref_genes.gtf 
```
and so on where the D0, D29, D50 (and the others) correspond to the different time points in days of the infection.
What I don't understand is how π, the mean number of differences per site among all sequences is computed when the script is ran for each sample separately.

Again, I apologize for the dummy questions.
Thanks again for your help !

**Comment by singing-scientist** [comment]
Greetings @PegahDan ! 

Assuming the vcfformat is the correct one for your file, this looks good to me — SNPGenie is being run for each sample (i.e., timepoint). Thus, π is simply being calculated for each timepoint (run of SNPGenie), specifically, as the mean number of pairwise differences between all sequences (reads) implied by the SNPs that are present in each VCF file. Does that answer the question, or have I missed the mark?

Yours,
Chase

**Comment by PegahDan** [comment]
Hi @singing-scientist !

I apologize for the late response. Your feed backs helped me a lot !! Thank you very much.
