### ISSUE TITLE
Can't find site When use CLC as SNP report

### ISSUE THREAD

**Issue by YangJingqii** [chasewnelson/SNPGenie#77]
Hi,
I generated txt according to the format of CLC, but there was no mutation in site_results.txt in SNPGenie, which was obviously abnormal. The reason why I wanted to generate clc was that I added some screening conditions to vcf, but I ran with the vcf before screening and it was possible to find out, I didn't know what the problem was. Could you take a look for me? Thank you very much!

```
Reference Position	Type	Reference	Allele	Count	Coverage	Frequency	Overlapping annotations
2378	snp	A	G	18	356	5.056179775280898	CDS:P
2591	snp	A	G	58	7434	0.7801990852838311	CDS:P
2594	snp	C	A	107	7439	1.438365371689743	CDS:P
2596	snp	C	A	63	7441	0.8466603951081844	CDS:P
2602	snp	A	G	43	7428	0.5788906838987614	CDS:P
2616	snp	C	A	207	7450	2.778523489932886	CDS:P
2618	snp	C	A	66	7455	0.8853118712273641	CDS:P
2621	snp	C	A	79	7453	1.0599758486515498	CDS:P
2623	snp	C	A	46	7465	0.6162089752176825	CDS:P
2624	snp	C	A	143	7467	1.9150930762019551	CDS:P
```

[E5.txt](https://github.com/user-attachments/files/17690754/E5.txt)

**Comment by singing-scientist** [comment]
HI @YangJingqii ! Thanks for the question.

The only two things I notice are (1) type should be "SNV" and (2) there should be a space after "CDS:", e.g., "CDS: P". I know those are very specific points but I hesitate to relax them, since they're exactly what CLC does (or did when I wrote this).

If that doesn't solve the problem please feel free to attached (or email) a small example set of three files so I can try running it and troubleshoot the problem.

Yours,
Chase

**Comment by YangJingqii** [comment]
That works! Thank you very much!!!

**Comment by singing-scientist** [comment]
Glad to hear! Feel free to reopen issue if another problem arises

**Comment by YangJingqii** [comment]
ok ,thanks again!
