### ISSUE TITLE
score in GTF file, parsing problem

### ISSUE THREAD

**Issue by WardDeb** [chasewnelson/SNPGenie#9]
Hi,

I've used prodigal to generate some GTF files that I use in SNPgenie downstream. I've noticed that if the score field has an actual value, SNPgenie fails saying that there are no + strand products in the GTF file (the score values are for example 120.5). If I remove the score values (by '.') this problem seems to be fixed. 

Kind regards,

Warddeb

**Comment by singing-scientist** [comment]
Thanks so much for catching this bug, @WardDeb ! I have updated the SNPGenie code — if you don't mind, please let me know if it now works with your original GTF file(s) (i.e., before replacing scores with '.'). If it is still not fixed, please share a sample GTF file, if you're willing, so that I may troubleshoot.

With gratitude,
Chase

**Comment by WardDeb** [comment]
Hi Chase,

Thanks for the quick fix! Problem seems to be resolved.

Kind regards,

Warddeb
